---
layout: post
title: Classstarter
subtitle: A test project in *Common Lisp* 
---

I really like Common Lisp, but I am only a hobby coder. I will create a project to learn and practice techniques and patterns for creating projects in Common Lisp.

* Classstarter what is

Classstarter will be an auction system for a market of seats at classes at my hackerspace.

** Approach

I will study and use techniques learned online, particularly following the *Atlanta Functional Programming Meetup* resources, currently available on Youtube at 
[Atlanta Functional Programming](https://www.youtube.com/channel/UCYg6qFXDE5SGT_YXhuJPU0A/videos)

*** Thoughts on design

What are the things?

Qvo Qvod?

Initially I'll use techniques described in [_Practical Common Lisp_](https://www.amazon.com/Practical-Common-Experts-Programming-Languages/dp/1430242906/), building and manipulating structures from lists.

I'll soon shift to using an SQL database, then probably use an ORM.

[Eitaro Fukamachi](https://github.com/fukamachi/) has made GREAT tools.

*** Entities

- Person
  - Name
  - Role
  - email address
  - phone number
  - paypal address
  
  - Instructor
  - Attendee
  - Administrator
- Event (not a specific occurence)
  - Description
  - Materials
  - Equipment
  - Pre-requisites
  - Time constraints
- Occurence
  - Event definition ID
  - Venue
  - Start
  - Stop
  - Attendee Max
  - Min fee
  - Min revenue
- Bid (for seat(s) at an Occurence
  - Occurence ID
  - Attendee ID
  - Seat Count
  - Bid per seat

*** 
